In [1]:
pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Question 1:

- create a NumPy array
- find the largest element
- find the index of the smalles element in array
- print the number of elements

In [3]:
ar1 = np.array([3, 6, 8,23, 54, 6, 13, 67, 85])
ar1.max()

np.int64(85)

In [4]:
ar1.argmin()

np.int64(0)

In [5]:
ar1.size
# return number of element

9

In [6]:
ar1.shape

(9,)

### Question2

- create an array contains 20 elements using randint function between 0-60
- reshape and get matrix
- reshape to get tensor

In [7]:
ar2 = np.random.randint(0, 60, 20)
ar2

array([20,  4, 39, 34, 19, 15,  7, 18, 30, 46, 36, 30, 36, 48, 47, 51, 57,
       41, 34, 32])

In [8]:
# reshape it to matrix
ar2.reshape(4, 5)

array([[20,  4, 39, 34, 19],
       [15,  7, 18, 30, 46],
       [36, 30, 36, 48, 47],
       [51, 57, 41, 34, 32]])

In [9]:
# reshape to tensor
ar2.reshape(2,2,5)

array([[[20,  4, 39, 34, 19],
        [15,  7, 18, 30, 46]],

       [[36, 30, 36, 48, 47],
        [51, 57, 41, 34, 32]]])

In [10]:
ar2.reshape(5,2,2)

array([[[20,  4],
        [39, 34]],

       [[19, 15],
        [ 7, 18]],

       [[30, 46],
        [36, 30]],

       [[36, 48],
        [47, 51]],

       [[57, 41],
        [34, 32]]])

### Question3

- create an array using arange function containg even number from 20 to 80
- reshape it as 5 rows and 6 columns
- then take a copy of it

In [13]:
ar3 = np.arange(20, 80, 2)
ar3

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78])

In [14]:
ar3 = ar3.reshape(5, 6)
ar3

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [16]:
ar4 = ar3.copy()
ar4

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

### Question 4

- split the ar4 horizontally from half
- split the ar4 into 3 vertical using array split
- split the ar4 into 3 herizontally using array split
- split the ar4 horizontally from index 5 using split

In [17]:
ar4

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [18]:
# split the ar4 horizontally from half
np.hsplit(ar4, 2)
# split horizontally from half

[array([[20, 22, 24],
        [32, 34, 36],
        [44, 46, 48],
        [56, 58, 60],
        [68, 70, 72]]),
 array([[26, 28, 30],
        [38, 40, 42],
        [50, 52, 54],
        [62, 64, 66],
        [74, 76, 78]])]

In [20]:
# split the ar4 into 3 vertical using array split
np.array_split(ar4, 3)
np.array_split(ar4, 3, axis=0)
# both are the same thing

[array([[20, 22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40, 42]]),
 array([[44, 46, 48, 50, 52, 54],
        [56, 58, 60, 62, 64, 66]]),
 array([[68, 70, 72, 74, 76, 78]])]

In [21]:
# split the ar4 into 3 herizontally using array split
np.array_split(ar4, 3, axis=1)
# splitting horizontally, from column

[array([[20, 22],
        [32, 34],
        [44, 46],
        [56, 58],
        [68, 70]]),
 array([[24, 26],
        [36, 38],
        [48, 50],
        [60, 62],
        [72, 74]]),
 array([[28, 30],
        [40, 42],
        [52, 54],
        [64, 66],
        [76, 78]])]

In [22]:
# split the ar4 horizontally from index 5 using split
np.split(ar4, [5], axis=1)

[array([[20, 22, 24, 26, 28],
        [32, 34, 36, 38, 40],
        [44, 46, 48, 50, 52],
        [56, 58, 60, 62, 64],
        [68, 70, 72, 74, 76]]),
 array([[30],
        [42],
        [54],
        [66],
        [78]])]

In [23]:
# transpose ar4
ar4.transpose
ar4.T
# both do the same thing

array([[20, 32, 44, 56, 68],
       [22, 34, 46, 58, 70],
       [24, 36, 48, 60, 72],
       [26, 38, 50, 62, 74],
       [28, 40, 52, 64, 76],
       [30, 42, 54, 66, 78]])

In [26]:
# resize ar4 10, 10
np.resize(ar4, (10, 10))

array([[20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

### Question 5

- a = np.random.randint(1,10,4).reshape(2,2)
- b = np.random.randint(10, 20, 6).reshape(3,2)
- concatenate a, b

In [33]:
a = np.random.randint(1,10,4).reshape(2,2)
a

array([[8, 8],
       [6, 2]])

In [29]:
b = np.random.randint(10, 20, 6).reshape(3,2)
b

array([[12, 18],
       [18, 14],
       [15, 18]])

In [36]:
np.concatenate((a, b), axis=0)

array([[ 8,  8],
       [ 6,  2],
       [12, 18],
       [18, 14],
       [15, 18]])

In [37]:
# reshape ar3 to 3 rows 10 columns
ar3

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [41]:
ar3 = np.reshape(ar3, (3, 10))
ar3

array([[20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78]])

In [45]:
# get the number 46 from ar3
ar3[1,3]

np.int64(46)

In [47]:
# get the data following data with slicing
# 48, 50, 52, 54
# 68, 70, 72, 74
ar3[1:, 4:8]

array([[48, 50, 52, 54],
       [68, 70, 72, 74]])

In [48]:
ar3[::2,::2]

array([[20, 24, 28, 32, 36],
       [60, 64, 68, 72, 76]])

### Question 6
- Use the randint function to generate a numpy array with 40 elements between 1 and 100.
- Reshape it to 5, 8.
- Print the numbers greater than 40 in another array.
- Print the numbers divisible by 5 in another array.

In [49]:
ar5 = np.random.randint(1,100,40).reshape(5,8)
ar5

array([[17, 14, 60, 49, 47, 62, 96, 62],
       [23, 45, 25, 68, 42, 24, 18, 42],
       [39, 55,  2, 79, 51, 30, 36, 45],
       [98,  1, 62, 80,  3, 52, 14, 69],
       [52,  7, 36,  5, 65, 27, 49, 66]])

In [52]:
ar6 = ar5[ar5 > 40]
ar6

array([60, 49, 47, 62, 96, 62, 45, 68, 42, 42, 55, 79, 51, 45, 98, 62, 80,
       52, 69, 52, 65, 49, 66])

In [54]:
ar7 = ar5[ar5%5==0]
ar7

array([60, 45, 25, 55, 30, 45, 80,  5, 65])

### Question 7

- create a numpy array shape (3, 4) filled with 1s, then add 6
- create a numpy array shape (2, 5) filled with 0s

In [57]:
ar8 = np.ones((3, 4), dtype=int)
ar8

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
ar10 = ar8 + 6

In [59]:
ar9 = np.arange(1, 5)
ar9

array([1, 2, 3, 4])

In [62]:
ar9 + ar10

array([[ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

### Question 11

- using ar3, create ones_like function and create new array contains only 1s ad add 4

In [64]:
np.ones_like(ar3) + 4

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [65]:
np.ones_like(ar3) + np.arange(1, 11)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

# Question 12

- linspace
- create 10 number from 20 t0 40 equally spaced

In [66]:
np.linspace(20, 40, 10)

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])